export const wasteData = [
  {
    id: 1,
    date: "Feb 12, 2024",
    trucks: "3",
    metal: "16",
    plastic: "16",
    wood: "16",
    paper: "16",
    liquid: "16",
    recycled: "80%",
  },
  {
    id: 2,
    date: "Feb 13, 2024",
    trucks: "4",
    metal: "20",
    plastic: "12",
    wood: "18",
    paper: "15",
    liquid: "14",
    recycled: "78%",
  },
  {
    id: 3,
    date: "Feb 14, 2024",
    trucks: "2",
    metal: "14",
    plastic: "18",
    wood: "15",
    paper: "13",
    liquid: "12",
    recycled: "75%",
  },
  {
    id: 4,
    date: "Feb 15, 2024",
    trucks: "5",
    metal: "22",
    plastic: "10",
    wood: "20",
    paper: "17",
    liquid: "19",
    recycled: "82%",
  },
  {
    id: 5,
    date: "Feb 16, 2024",
    trucks: "3",
    metal: "18",
    plastic: "14",
    wood: "16",
    paper: "14",
    liquid: "15",
    recycled: "79%",
  },
  {
    id: 6,
    date: "Feb 17, 2024",
    trucks: "3",
    metal: "15",
    plastic: "15",
    wood: "15",
    paper: "15",
    liquid: "15",
    recycled: "76%",
  },
  {
    id: 7,
    date: "Feb 18, 2024",
    trucks: "4",
    metal: "21",
    plastic: "13",
    wood: "18",
    paper: "12",
    liquid: "17",
    recycled: "83%",
  },
  {
    id: 8,
    date: "Feb 19, 2024",
    trucks: "2",
    metal: "17",
    plastic: "16",
    wood: "14",
    paper: "16",
    liquid: "16",
    recycled: "77%",
  },
  {
    id: 9,
    date: "Feb 20, 2024",
    trucks: "3",
    metal: "16",
    plastic: "20",
    wood: "15",
    paper: "18",
    liquid: "13",
    recycled: "80%",
  },
];

export const wasteDataColumns = [
  {
    name: "Date",
    selector: (row) => row?.date,
  },
  {
    name: "No. of Trucks",
    selector: (row) => row?.trucks,
  },
  {
    name: "Metal",
    selector: (row) => row?.metal,
  },
  {
    name: "Plastic",
    selector: (row) => row?.plastic,
  },
  {
    name: "Wood",
    selector: (row) => row?.wood,
  },
  {
    name: "Paper",
    selector: (row) => row?.paper,
  },
  {
    name: "Liquid",
    selector: (row) => row?.liquid,
  },
  {
    name: "Recycled",
    selector: (row) => <div>{row?.recycled}</div>,
  },
];
