export const initialSensorData = [
    {
      id: 1,
      sensorName: "Bin-001",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-10",
      status: "full",
    },
    {
      id: 2,
      sensorName: "Bin-002",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-12",
      status: "half",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    {
      id: 3,
      sensorName: "Bin-003",
      sensorType: "Bin Sensor",
      createdDate: "2024-02-15",
      status: "empty",
    },
    // Add more sensor objects as needed
  ];
  